### ISSUE TITLE
Netherite Textures

### ISSUE THREAD

**Issue by ThexXTURBOXx** [ThexXTURBOXx/balkons-weaponmod#1]
@Squeekblach @Sunconure11
Long time no hear! And, to be honest, I am very sorry for that - it was my fault.
It was only recently I wanted to do something like [Reforged](https://github.com/ThexXTURBOXx/Reforged) again.
However, first, I wanted to finish it. And here we are! The current versions are under review and I feel very relieved :)
Now, since I am still very bad in regards to making textures, so I just included some sporadic Netherite weapon textures.
Maybe, one of you has some time left to improve them/make better ones? I would be very thankful for that - so thank you very much in advance!
But, please, do not take this as a must. If you have better things to do, you do not even have to reply.
Of course I will also add you in the credits of this mod then (and, if you want, also on CurseForge and/or Modrinth)!

So, again, thank you very much in advance and have a great day! :)

Edit: Forgot to mention: The respective textures can be found [here](https://github.com/ThexXTURBOXx/Balkons-WeaponMod-Legacy/tree/1.21/common/src/main/resources/assets/weaponmod/textures/item) (all the files with `.netherite.png` at the end).

**Comment by ThexXTURBOXx** [comment]
Again, you don't need to respond :)
Since I have not yet heard back from you, I guess that you are busy with more important things!
So, I will just pin this issue - maybe someone else from the community wants to take this over.

Thank you for considering, though!

**Comment by Squeekblach** [comment]
Hey - sorry haha. I was about to reply but kept trying to guess my old github login, got temporarily restricted, and forgot to try again later.

I'd be happy to help whip up whatever new textures are needed. I've got some spare time so I'll work on some more-correct netherite ones now. Let me know if there's anything else.

**Comment by Squeekblach** [comment]
Here they are - I had to take a few liberties with them since the netherite textures only exist in the new vanilla texture form. But these should fit in side by side with the vanilla netherite tools.

Let me know if I missed anything.
[reforged_netherite.zip](https://github.com/user-attachments/files/15981174/reforged_netherite.zip)

**Comment by ThexXTURBOXx** [comment]
Oh, thank you very much and welcome back! That was a surprise for sure, but a welcome one :)

> Hey - sorry haha. I was about to reply but kept trying to guess my old github login, got temporarily restricted, and forgot to try again later.

That sounds like a fun journey ;)

> I'd be happy to help whip up whatever new textures are needed. I've got some spare time so I'll work on some more-correct netherite ones now. Let me know if there's anything else.

Perfect, thank you very much! For now, the Netherite textures are the most pressing issue. I will focus on stability and balancing issues first before I (might) add more weapons.
However, when I'm satisfied at some point, I will contact you again for sure! So, thank you very much for your offer!

> Here they are - I had to take a few liberties with them since the netherite textures only exist in the new vanilla texture form. But these should fit in side by side with the vanilla netherite tools.

They look very good! Good job! I will add the textures to the repository tomorrow in the evening - today I am travelling to a meeting for work.

> Let me know if I missed anything.

I think you might have missed the boomerang :)

Edit: One more thing! Do you have a CurseForge and/or Modrinth account? This way, I could add you to the project as "Artist" if you want!

**Comment by Squeekblach** [comment]
> They look very good! Good job!

Thank you!

Here's the boomerang. I also fixed a small positioning issue with the battleaxe (it was off by a pixel).
![boomerang_netherite](https://github.com/ThexXTURBOXx/Balkons-WeaponMod-Legacy/assets/16748858/71a8c99a-7dff-45f7-a88d-85d904b91b0c)
![battleaxe_netherite](https://github.com/ThexXTURBOXx/Balkons-WeaponMod-Legacy/assets/16748858/f2ab5150-ef46-431e-94be-3864cc1d02f2)

>One more thing! Do you have a CurseForge and/or Modrinth account? This way, I could add you to the project as "Artist" if you want!

Sure, My curseforge username is 'Squeekblach', same as here. Thanks!

**Comment by Sunconure11** [comment]
If you touch any other mods for cross-compat, do note that Expanded Armory has done some already

https://www.curseforge.com/minecraft/mc-mods/expanded-armory

**Comment by ThexXTURBOXx** [comment]
> Here's the boomerang. I also fixed a small positioning issue with the battleaxe (it was off by a pixel).

Perfect, thank you very much! :)
Sadly, my train is an hour late because of Deutsche-Bahn-things.
So, I don't know yet whether I will be able to work on the mod tonight, but at least I have already added you to the project on CurseForge!

**Comment by ThexXTURBOXx** [comment]
I couldn't resist ;)
The netherite textures have been swapped out and they look even better ingame!
Thank you very much, the new textures also look a bit more "heartful" than my miserable attempts - I still don't really understand how one is able to make the colours look so much better (well, I know that at least one part of the problem is my colorblindness... But I don't know about the rest)

So, again, thank you very much for what you've done already - and as already said: I will be in contact when I am planning to add new wepaons :)
